spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appType: GS
        appName: gs-yarn-appmodel
        applicationBaseDir: /app/
        applicationDir: /app/gs-yarn-appmodel/
        client:
            clientClass: org.springframework.yarn.client.DefaultApplicationYarnClient
            files:
              - "file:build/libs/gs-yarn-appmodel-container-0.1.0.jar"
              - "file:build/libs/gs-yarn-appmodel-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: gs-yarn-appmodel-appmaster-0.1.0.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: gs-yarn-appmodel-container-0.1.0.jar
